name: Build Image and Create Release

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-24.04-arm

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy env
        run: cp .env.example .env

      - name: Get SSH keys from GitHub
        run: wget https://github.com/${{ github.repository_owner }}.keys -O ./input/config/authorized_keys

      - name: Run build script
        run: ./build_image.sh

      - name: Create tag
        id: create-tag
        run: echo "RELEASE_TAG=v$(date +'%Y-%m-%d')-${GITHUB_SHA:0:5}" >> "$GITHUB_ENV"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.RELEASE_TAG }}"
          name: "Release ${{ env.RELEASE_TAG }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_release.outputs.tag_name }}
          files: |
            output/sdcard.img.gz
            output/sdcard.img.gz.sha256
            output/sdcard_update.img.gz
            output/sdcard_update.img.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}